"use client";

/**
 * Client-side utility to copy report to clipboard
 */

interface ReportData {
  label: string;
  score: number;
  target: {
    original: string;
    display: string;
    baseDomain: string;
    via: string[];
  };
  reasons: string[];
  meta: {
    ageDays: number | null;
    isGateway: boolean;
    isVendorAsset: boolean;
  };
}

export async function copyReport(data: ReportData): Promise<void> {
  const lines: string[] = [];
  
  lines.push("═══════════════════════════════════════");
  lines.push("LinkCheck Report");
  lines.push("═══════════════════════════════════════");
  lines.push("");
  
  lines.push(`RISK LEVEL: ${data.label} (${data.score}/100)`);
  lines.push("");
  
  lines.push("TARGET:");
  lines.push(`  Final URL: ${data.target.display}`);
  lines.push(`  Base Domain: ${data.target.baseDomain}`);
  
  if (data.target.via.length > 0) {
    lines.push(`  Via: ${data.target.via.join(", ")}`);
  }
  
  if (data.target.original !== data.target.display) {
    lines.push(`  Original: ${data.target.original}`);
  }
  lines.push("");
  
  lines.push("FINDINGS:");
  for (const reason of data.reasons) {
    lines.push(`  • ${reason}`);
  }
  lines.push("");
  
  if (data.meta.ageDays !== null) {
    lines.push(`Domain age: ${data.meta.ageDays} days`);
  }
  
  lines.push("");
  lines.push("───────────────────────────────────────");
  lines.push("Generated by LinkCheck");
  lines.push("No data stored • Privacy-first");
  lines.push("═══════════════════════════════════════");
  
  const text = lines.join("\n");
  
  await navigator.clipboard.writeText(text);
}



